/**
 * Created by ayaz on 12/9/15.
 */

var mongoose = require('mongoose');
var blobSchema = new mongoose.Schema({
    _id: String,
    contactperson: String,
    name: String,
    email: String,
    mobile: String,
    tollfree: String,
    contact: String,
    fax: String,
    website: String,
    complat: String,
    complong: String,
    mappointer: String,
    comprating: String,
    rating: String,
    HoursOfOperation: String,
    Catalogue: { type: mongoose.Schema.Types.Mixed, default: {} },
    videoUrl: String,
    overallRatingsChart: { type: mongoose.Schema.Types.Mixed, default: {} },
    ratingsOverTimeChart: { type: mongoose.Schema.Types.Mixed, default: {} },
    paymentModes: String,
    alsoListedIn: { type: mongoose.Schema.Types.Mixed, default: {} },
    totalReviews: String,
    Reviews: { type: mongoose.Schema.Types.Mixed, default: {} },
    services: { type: mongoose.Schema.Types.Mixed, default: {} },
    YOE: String,
    rateThis: String,
    bd_detailshow: { type: mongoose.Schema.Types.Mixed, default: {} },
    alsolist_counts: String,
    totJdReviews: String,
    guarantee: String,
    verified: String,
    building: String,
    street: String,
    area: String,
    pincode: String,
    VNumber: String,
    paidStatus: String,
    fratings: { type: mongoose.Schema.Types.Mixed, default: {} },
    myratings: { type: mongoose.Schema.Types.Mixed, default: {} },
    vertical_data: { type: mongoose.Schema.Types.Mixed, default: {} },
    price_range: String,
    other_city_num: { type: mongoose.Schema.Types.Mixed, default: {} },
    sharedt_url: String,
    Sharerating: String,
    closeddown_flag: Number,
    price_tag_d: String,
    IsDeal: Number,
    docId: String,
    address: String,
    categories: String,
    landmark: String,
    an: { type: mongoose.Schema.Types.Mixed, default: {} },
    city: String,
    myRatings: [],
    thumbnail: String,
    isVerified: { type: Boolean, default: false },
    isPhoneVerified: { type: Boolean, default: false },
    isAddressVerified: { type: Boolean, default: false },
    businessModel: String,
    charges: String,
    dob: { type: Date, default: '01/01/1975' },
    dateEnrolled: { type: Date, default: Date.now },
    phone: String,
    locality: String,
    updatedAt: { type: Date, default: Date.now }
});

mongoose.model('Blob', blobSchema, 'babysitters');